# Intrusion Attack Detection Project Framework - Data Science

Upload files

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data9_1.csv to data9_1.csv


In [ ]:
import pandas as pd
import numpy as np

Read datasheet with the help of pandas

In [ ]:
datasheet = pd.read_csv("data9_1.csv")
datasheet.head()

Marker  R1-PA1:VH     R1-PM1:V   R1-PA2:VH     R1-PM2:V   R1-PA3:VH  \
0       1  -5.781144  132462.0854 -125.752777  132411.9389  114.236325   
1       1  -3.833088  132863.2577 -123.804720  132838.1845  116.178652   
2       1  -3.729955  132687.7448 -123.695858  132637.5983  116.281785   
3       1  -3.787251  132361.7923 -123.758884  132311.6458  116.230218   
4       1  -3.878924  132286.5725 -123.850557  132236.4260  116.132816   

      R1-PM3:V  R1-PA4:IH   R1-PM4:I   R1-PA5:IH  ...  control_panel_log3  \
0  132537.3052   0.784952  264.04462 -124.251627  ...                   0   
1  132938.4775   1.329262  268.25615 -122.475458  ...                   0   
2  132737.8914   0.899544  270.27036 -122.504106  ...                   0   
3  132411.9389  -0.383882  274.84811 -122.985391  ...                   0   
4  132336.7191  -0.979758  276.67921 -123.128630  ...                   0   

   control_panel_log4  relay1_log  relay2_log  relay3_log  relay4_log  \
0                   0           0           0           0           0   
1                   0           0           0           0           0   
2                   0           0           0           0           0   
3                   0           0           0           0           0   
4                   0           0           0           0           0   

   snort_log1  snort_log2  snort_log3  snort_log4  
0           0           0           0           0  
1           0           0           0           0  
2           0           0           0           0  
3           0           0           0           0  
4           0           0           0           0  

[5 rows x 129 columns]

info() -> infromation about the data

In [ ]:
datasheet.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15582 entries, 0 to 15581
Data columns (total 129 columns):
 #    Column              Dtype  
---   ------              -----  
 0    Marker              int64  
 1    R1-PA1:VH           float64
 2    R1-PM1:V            float64
 3    R1-PA2:VH           float64
 4    R1-PM2:V            float64
 5    R1-PA3:VH           float64
 6    R1-PM3:V            float64
 7    R1-PA4:IH           float64
 8    R1-PM4:I            float64
 9    R1-PA5:IH           float64
 10   R1-PM5:I            float64
 11   R1-PA6:IH           float64
 12   R1-PM6:I            float64
 13   R1-PA7:VH           float64
 14   R1-PM7:V            float64
 15   R1-PA8:VH           float64
 16   R1-PM8:V            float64
 17   R1-PA9:VH           float64
 18   R1-PM9:V            float64
 19   R1-PA10:IH          float64
 20   R1-PM10:I           float64
 21   R1-PA11:IH          float64
 22   R1-PM11:I           float64
 23   R1-PA12:IH          float64
 24   

Selected only those columns which are required to make our desired model. So we copy that columns from that main datasheet and decleared into 3 different variable as (rds_phase1, rds_phase2, rds_phase3)

Step:1 Select required columns for phase 1

Here, declears that all rows with specified columns data selected by using -> .loc[starting_row : ending_row, ["Selected comuns"........]

In [ ]:
##required datasheet rds for phase_1 or R-phase
# rds_phase1 = datasheet.loc[:,['R1-PA1:VH','R1-PA4:IH','R1-PM4:I','R1-PM1:V']]
# rds_phase1.head()

Here, declears that only one row(0) with specified columns data selected by using -> .loc[starting_row : ending_row, ["Selected comuns"........]

In [ ]:
# required datasheet rds for phase_1 or R-phase
rds_phase1 = datasheet.loc[0:0,['R1-PA1:VH','R1-PA4:IH','R1-PM4:I','R1-PM1:V']]
rds_phase1

R1-PA1:VH  R1-PA4:IH   R1-PM4:I     R1-PM1:V
0  -5.781144   0.784952  264.04462  132462.0854

Creat a loop so that all rows data are fitted to in array as a same order

Find out the size of array and then matched with the desired model array

In [ ]:
# see the error message to find the array of size
# numpy.reshape(array, shape, order = 'C')
# shape array with 4 rows and 2 columns

# rds_phase1.to_numpy().reshape(2,2,2)

From above,we know that the size of this array 62328
and now we reshape it as a (2x2) 3D-matrix

In [ ]:
# we have found array of size: 62328
# now to convert dataframe to 3D
# we have to divide 62328 in 3 parts such that multiplication of these 3 parts give us 42168
# arr_phase1 = rds_phase1.to_numpy().reshape(15582, 2, 2)
# arr_phase1

In [ ]:
rds_phase1.to_numpy().reshape(2,2,2)

ValueError: ignored

From above,we know that the size of this array 4
and now we reshape it as a (1x2x2) 3D-matrix

In [ ]:
arr_phase1 = rds_phase1.to_numpy().reshape(1, 2, 2)
arr_phase1

array([[[-5.78114415e+00,  7.84952179e-01],
        [ 2.64044620e+02,  1.32462085e+05]]])

.ndim -> used to find out array dimension

In [ ]:
# display dimensions
# 3 means the dataframe is 3D
arr_phase1.ndim

3

Step:1 Select required columns for phase 2 and       //* follow same steps as previously done

In [ ]:
# # required datasheet rds for phase_2 or Y-phase
# rds_phase2 = datasheet.loc[:,['R1-PA2:VH','R1-PA5:IH','R1-PM5:I','R1-PM2:V']]
# rds_phase2.head()

In [ ]:
rds_phase2 = datasheet.loc[0:0,['R1-PA2:VH','R1-PM5:I','R1-PM2:V','R1-PA5:IH']]
rds_phase2.head()

R1-PA2:VH   R1-PM5:I     R1-PM2:V   R1-PA5:IH
0 -125.752777  279.60897  132411.9389 -124.251627

In [ ]:
# arr_phase2 = rds_phase2.to_numpy().reshape(15582, 2, 2)
# arr_phase2

In [ ]:
arr_phase2 = rds_phase2.to_numpy().reshape(1, 2, 2)
arr_phase2

array([[[-1.25752777e+02,  2.79608970e+02],
        [ 1.32411939e+05, -1.24251627e+02]]])

In [ ]:
arr_phase2.ndim

3

Step:1 Select required columns for phase 3 and       //* follow same steps as previously done

In [ ]:
# required datasheet rds for phase_3 or B-phase
# rds_phase3 = datasheet.loc[:,['R1-PA3:VH','R1-PA6:IH','R1-PM6:I','R1-PM3:V']]
# rds_phase3

In [ ]:
rds_phase3 = datasheet.loc[0:0,['R1-PA3:VH','R1-PM6:I','R1-PM3:V','R1-PA6:IH']]
rds_phase3

R1-PA3:VH   R1-PM6:I     R1-PM3:V  R1-PA6:IH
0  114.236325  260.56553  132537.3052   121.0889

In [ ]:
# arr_phase3 = rds_phase3.to_numpy().reshape(15582, 2, 2)
# arr_phase3

In [ ]:
arr_phase3 = rds_phase3.to_numpy().reshape(1, 2, 2)
arr_phase3

array([[[1.14236325e+02, 2.60565530e+02],
        [1.32537305e+05, 1.21088900e+02]]])

In [ ]:
arr_phase3.ndim

3

Concatenation of array

In [ ]:
arr_phase1

array([[[-5.78114415e+00,  7.84952179e-01],
        [ 2.64044620e+02,  1.32462085e+05]]])

In [ ]:
arr_phase2

array([[[-1.25752777e+02,  2.79608970e+02],
        [ 1.32411939e+05, -1.24251627e+02]]])

In [ ]:
arr_phase3

array([[[1.14236325e+02, 2.60565530e+02],
        [1.32537305e+05, 1.21088900e+02]]])

In [ ]:
# Concatenation method (axis= 1 for same column) and (axis= -1 for same row)
print(np.concatenate((arr_phase1, arr_phase2, arr_phase3), axis = 1))

[[[-5.78114415e+00  7.84952179e-01]
  [ 2.64044620e+02  1.32462085e+05]
  [-1.25752777e+02  2.79608970e+02]
  [ 1.32411939e+05 -1.24251627e+02]
  [ 1.14236325e+02  2.60565530e+02]
  [ 1.32537305e+05  1.21088900e+02]]]


Create a file _Demo Purpose

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings

import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import sklearn.metrics as metrics

In [ ]:
from sklearn.neighbors import KNeighborsClassifier as KNN
import numpy as np

# Load dataset
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=2018)

# import KNeighborsClassifier model
knn = KNN(n_neighbors=3)

# train model
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [ ]:
from joblib import Parallel, delayed
import joblib


# Save the model as a pickle in a file
joblib.dump(knn, 'filename.pkl')

# Load the model from the file
knn_from_joblib = joblib.load('filename.pkl')

# Use the loaded model to make predictions
knn_from_joblib.predict(X_test)


array([0, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 0,
       2, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 1, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2,
       1])